name: publish-release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        # GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
      with:
        title: ${{ github.ref_name }}